=== Pocket/recommendation-api/app/json/slate_config.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/slates",
    "type": "object",
    "title": "The Slates Schema",
    "required": [
      "id",
      "displayName",
      "description",
      "experiments"
    ],
    "properties": {
      "id": {
        "$id": "#/properties/id",
        "type": "string",
        "format": "uuid",
        "title": "The ID Schema",
        "default": "",
        "examples": [
          "c410516f-18b3-46a1-b356-c7c003de2b53"
        ],
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "displayName": {
        "$id": "#/properties/displayName",
        "type": "string",
        "title": "The Display Name Schema",
        "default": "",
        "examples": [
          "Trending Articles"
        ],
        "pattern": "^(.+)$"
      },
      "curatorTopicLabel": {
        "$id": "#/properties/displayName",
        "type": "string",
        "title": "The Curator Topic Label Schema",
        "default": "",
        "examples": [
          "Self Improvement"
        ],
        "enum" : [
          "Business",
          "COVID-19",
          "Career",
          "Education",
          "Entertainment",
          "Food",
          "Gaming",
          "Health & Fitness",
          "Parenting",
          "Personal Finance",
          "Politics",
          "Science",
          "Self Improvement",
          "Sports",
          "Technology",
          "Travel"
        ],
        "pattern": "^(.+)$"
      },
      "description": {
        "$id": "#/properties/description",
        "type": "string",
        "title": "The Description Schema",
        "default": "",
        "examples": [
          "New perspectives, intriguing deep-dives, and timeless classics"
        ],
        "pattern": "^(.+)$"
      },
      "internalDescription": {
        "$id": "#/properties/internalDescription",
        "type": "string",
        "title": "The Internal Description Schema",
        "description": "A slate description for internal use only",
        "default": "",
        "examples": [
          "Curated items including syndicated that are at most a week old"
        ],
        "pattern": "^(.+)$"
      },
      "experiments": {
        "$id": "#/properties/experiments",
        "type": "array",
        "title": "The Experiments Schema",
        "items": {
          "$id": "#/properties/experiments/items",
          "type": "object",
          "title": "The Experiments Items Schema",
          "required": [
            "description",
            "candidateSets",
            "rankers"
          ],
          "properties": {
            "description": {
              "$id": "#/properties/experiments/properties/description",
              "type": "string",
              "title": "The Experiment Description Schema",
              "default": "",
              "examples": [
                "TS window 30"
              ],
              "pattern": "^(.+)$"
            },
            "candidateSets": {
              "$id": "#/properties/experiments/properties/candidateSets",
              "type": "array",
              "title": "The Experiment Candidate Sets Schema",
              "default": null,
              "uniqueItems": true,
              "items": {
                "$id": "#/properties/experiments/properties/candidateSets/items",
                "type": "string",
                "format": "uuid",
                "title": "The Experiment Candidate Set Items Schema",
                "default": "",
                "examples": [
                  "39d0dc54-f6f8-4f13-bea4-4320b3bd8217",
                  "recit-personalized/bestof",
                  "recit-personalized/curated",
                  "recit-personalized/syndicated"
                ],
                "pattern": "^([0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}|recit-personalized\\/(bestof|syndicated|curated))$"
              }
            },
            "rankers": {
              "$id": "#/properties/experiments/properties/rankers",
              "type": "array",
              "title": "The Experiment Rankers Schema",
              "default": null,
              "uniqueItems": true,
              "items": {
                "$id": "#/properties/experiments/properties/rankers/items",
                "type": "string",
                "enum": [
                  "pubspread",
                  "top5-items",
                  "top15-items",
                  "top30-items",
                  "top45-items",
                  "thompson-sampling-1day",
                  "thompson-sampling-7day",
                  "thompson-sampling-14day",
                  "thompson-sampling-28day",
                  "firefox-thompson-sampling-15minute"
                ],
                "title": "The Experiment Ranker Items Schema",
                "default": "",
                "examples": [
                  "pubspread",
                  "top30-items"
                ],
                "pattern": "^(.+)$"
              }
            },
            "weight": {
              "$id": "#/properties/experiments/properties/weight",
              "type": "number",
              "title": "The Experiment Weight Schema",
              "default": 1,
              "examples": [
                1,
                0.1
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    }
  }
}

=== Pocket/recommendation-api/tests/assets/json/slate_configs.json
[
  {
   "id": "c410516f-18b3-46a1-b356-c7c003de2b53",
   "displayName": "Trending Articles",
   "description": "Curated articles within the last week that have high cascade probability",
   "experiments": [
     {
       "description": "TS window 30",
       "candidateSets": [
         "39d0dc54-f6f8-4f13-bea4-4320b3bd8217",
         "df8a86c1-8b40-48bf-b85d-c144ed96c3fc"
       ],
       "rankers": []
     },
     {
       "description": "TS window 15",
       "candidateSets": [
         "40d0dc54-f6f8-4f13-bea4-4320b3bd8218",
         "ab8a86c1-8b40-48bf-b85d-c144ed96c3fd"
       ],
       "rankers": [
         "top15-items",
         "thompson-sampling-28day",
         "pubspread"
       ],
       "weight": 0.5
     }
   ]
 },
 {
   "id": "b410516f-18b3-1337-b356-c7c003de2b42",
   "displayName": "Bending Particles",
   "description": "Bended particles within the last week that have high dawn probability",
   "experiments": [
     {
       "description": "TS window 15",
       "candidateSets": [
         "41d0dc54-f6f8-4f13-bea4-4320b3bd8219",
         "cd8a86c1-8b40-48bf-b85d-c144ed96c3fe"
       ],
       "rankers": [
         "thompson-sampling-28day",
         "top15-items"
       ],
       "weight": 0.2
     },
     {
       "description": "PubSpread Candidates",
       "candidateSets": [
         "42d0dc54-f6f8-4f13-bea4-4320b3bd8220",
         "ef8a86c1-8b40-48bf-b85d-c144ed96c3ff"
       ],
       "rankers": [
         "pubspread"
       ]
     }
   ]
 }
]
